# Macros needed by SELinux
%global selinuxtype targeted
%global modulename  platform_telemetry_agent

Summary:        An agent for managing and updating metric and log configurations
Name:           platform-telemetry-agent
Version:        1.4.0
Release:        1%{?dist}
License:        Apache-2.0
Vendor:         Intel Corporation
Distribution:   Edge Microvisor Toolkit
Group:          Applications/Text
URL:            https://github.com/open-edge-platform/edge-node-agents
Source0:        %{url}/archive/refs/tags/%{name}/v%{version}.tar.gz#/%{name}-%{version}.tar.gz
Source1:        %{name}.service
Source2:        env_wrapper.sh
Source3:        %{name}.conf
Source4:        platform_telemetry_agent.te
Source5:        platform_telemetry_agent.fc
%global debug_package %{nil}
%global _build_id_links none
%global prefix /usr
# The source tarball containing the platform telemetry agent source code with vendor modules.
# Source tarball is generated by using Makefile and vendor modules is generated using "go mod vendor".
BuildRequires:  golang
BuildRequires:  systemd-rpm-macros
BuildRequires:  selinux-policy-devel
Requires(pre):  %{_bindir}/systemd-sysusers
Requires:       dmidecode
Requires:       (%{name}-selinux if selinux-policy-targeted)

%description
Platform Telemetry Agent for OBaaS manages and updates node metric and log configurations,
re-executing metric and log collectors with the latest configuration

%package        selinux
Summary:        SELinux security policy for platform-telemetry-agent
Requires(post): platform-telemetry-agent = %{version}-%{release}
Requires:       fluent-bit-selinux
BuildArch:      noarch
%{?selinux_requires}

%description    selinux
SELinux security policy for platform-telemetry-agent.

%prep
%setup -q

%build
make ptabuild GO_MOD=vendor

mkdir selinux
cp -p %{SOURCE4} selinux/
cp -p %{SOURCE5} selinux/

make -f %{_datadir}/selinux/devel/Makefile %{modulename}.pp

%install
make install DESTDIR=%{buildroot} PREFIX=%{prefix}

install -d -m 755 %{buildroot}%{_sysconfdir}/edge-node/node/confs
install -m 644 configs/platform-telemetry-agent.yaml %{buildroot}%{_sysconfdir}/edge-node/node/confs/platform-telemetry-agent.yaml
install -m 644 configs/telegraf-host-gold.yaml %{buildroot}%{_sysconfdir}/edge-node/node/confs/telegraf-host-gold.yaml
install -m 644 configs/telegraf-cluster-gold.yaml %{buildroot}%{_sysconfdir}/edge-node/node/confs/telegraf-cluster-gold.yaml
install -m 644 configs/fluentbit-host-gold.yaml %{buildroot}%{_sysconfdir}/edge-node/node/confs/fluentbit-host-gold.yaml
install -m 644 configs/fluentbit-cluster-gold.yaml %{buildroot}%{_sysconfdir}/edge-node/node/confs/fluentbit-cluster-gold.yaml
install -m 744 %{SOURCE2} %{buildroot}%{_sysconfdir}/edge-node/node/confs/%{name}

mkdir -p %{buildroot}%{_unitdir}
cp %{SOURCE1} %{buildroot}%{_unitdir}

install -d %{buildroot}%{_sysconfdir}/sudoers.d
install configs/sudoers.d/platform-telemetry-agent %{buildroot}%{_sysconfdir}/sudoers.d

mkdir -p %{buildroot}%{_sysusersdir}
install -D -m 644 %{SOURCE3} %{buildroot}%{_sysusersdir}/%{name}.conf

mkdir -p %{buildroot}%{_defaultlicensedir}/%{name}
cp copyright %{buildroot}%{_defaultlicensedir}/%{name}

mkdir -p %{buildroot}%{_datadir}/selinux/packages
install -m 644 %{modulename}.pp %{buildroot}%{_datadir}/selinux/packages/%{modulename}.pp

%files    selinux
%{_datadir}/selinux/packages/%{modulename}.pp

%post     selinux
%selinux_modules_install -s %{selinuxtype} %{_datadir}/selinux/packages/%{modulename}.pp
# Apply the file contexts
/sbin/restorecon -Rv /etc/edge-node/node/platform-telemetry-agent
/sbin/restorecon -Rv /etc/edge-node/node/confs/platform-telemetry-agent.yaml
/sbin/restorecon -Rv /etc/edge-node/node/confs/telegraf-host-gold.yaml
/sbin/restorecon -Rv /etc/edge-node/node/confs/telegraf-cluster-gold.yaml
/sbin/restorecon -Rv /etc/edge-node/node/confs/fluentbit-host-gold.yaml
/sbin/restorecon -Rv /etc/edge-node/node/confs/fluentbit-cluster-gold.yaml
/sbin/restorecon -Rv /etc/intel_edge_node/tokens/platform-telemetry-agent/access_token
/sbin/restorecon -Rv /tmp/fluentbit-tmp.conf
/sbin/restorecon -Rv /tmp/fluentbit-cluster-tmp.conf
/sbin/restorecon -Rv /tmp/telegraf-tmp.conf
/sbin/restorecon -Rv /tmp/telegraf-tmp-cluster.conf
/sbin/restorecon -Rv /etc/telegraf/telegraf.conf
/sbin/restorecon -Rv /etc/fluent-bit/fluent-bit.conf

%postun   selinux
%selinux_modules_uninstall -s %{selinuxtype} %{modulename}

%files
%{prefix}/bin/%{name}
%config(noreplace) %attr(-, -, bm-agents) %{_sysconfdir}/edge-node/node/confs
%config %attr(-, platform-telemetry-agent, bm-agents) %{_sysconfdir}/edge-node/node/confs/platform-telemetry-agent.yaml
%config %attr(-, platform-telemetry-agent, bm-agents) %{_sysconfdir}/edge-node/node/confs/telegraf-host-gold.yaml
%config %attr(-, platform-telemetry-agent, bm-agents) %{_sysconfdir}/edge-node/node/confs/telegraf-cluster-gold.yaml
%config %attr(-, platform-telemetry-agent, bm-agents) %{_sysconfdir}/edge-node/node/confs/fluentbit-host-gold.yaml
%config %attr(-, platform-telemetry-agent, bm-agents) %{_sysconfdir}/edge-node/node/confs/fluentbit-cluster-gold.yaml
%config %attr(-, platform-telemetry-agent, bm-agents) %{_sysconfdir}/edge-node/node/confs/%{name}
%{_unitdir}/%{name}.service
%config %{_sysconfdir}/sudoers.d/platform-telemetry-agent
%{_sysusersdir}/%{name}.conf

%license %{_defaultlicensedir}/%{name}/copyright

%pre
%sysusers_create_package %{name} %{SOURCE3}

%post
#!/bin/sh
set -e

# Commands to run after installation
echo "Running post-installation script..."

echo "Assigning KUBECONFIG Start..."
if ! grep -q "KUBECONFIG=%{_sysconfdir}/rancher/rke2/rke2.yaml" %{_sysconfdir}/environment; then
    echo KUBECONFIG=%{_sysconfdir}/rancher/rke2/rke2.yaml | tee -a %{_sysconfdir}/environment
fi
echo "Assigning KUBECONFIG End"

# Reload systemd manager configuration
%systemd_post platform-telemetry-agent.service

%preun
# Before uninstallation, stop the service
%systemd_preun platform-telemetry-agent.service

%postun
# If this is an uninstall (not an upgrade), disable the service
%systemd_postun platform-telemetry-agent.service

%changelog
* Wed Jun 04 2025 Rajeev Ranjan <rajeev2.ranjan@intel.com> - 1.4.0-1
- Add backoff/retry on northbound grpc interfaces

* Thu Apr 03 2025 Rajeev Ranjan <rajeev2.ranjan@intel.com> - 1.3.1-1
- Update common to 1.6.8

* Wed Apr 02 2025 Christopher Nolan <christopher.nolan@intel.com> - 1.3.0-1
- Upgrade agent version

* Tue Mar 25 2025 Christopher Nolan <christopher.nolan@intel.com> - 1.2.9-1
- Update configuration and agent binary paths to use edge-node/

* Mon Mar 24 2025 Rajeev Ranjan <rajeev2.ranjan@intel.com> - 1.2.8-1
- Send status to Node Agent
- Conditional import on common.mk

* Fri Mar 21 2025 Anuj Mittal <anuj.mittal@intel.com> - 1.1.19-12
- Bump Release to rebuild

* Mon Mar 10 2025 Christopher Nolan <christopher.nolan@intel.com> - 1.1.19-11
- Fix typo in URL

* Mon Mar 10 2025 Christopher Nolan <christopher.nolan@intel.com> - 1.1.19-10
- Update URL for agents

* Mon Mar 3 2025 Jia Yong Tan <jia.yong.tan@intel.com> - 1.1.19-9
- Update SELinux policy.

* Tue Feb 18 2025 Suh Haw Teoh <suh.haw.teoh@intel.com> - 1.1.19-8
- Re-apply systemd hardening

* Wed Jan 22 2025 Anuj Mittal <anuj.mittal@intel.com> - 1.1.19-7
- Revert systemd service hardening changes

* Mon Jan 20 2025 Suh Haw Teoh <suh.haw.teoh@intel.com> - 1.1.19-6
- Update service file for systemd hardening

* Fri Jan 17 2025 Jia Yong Tan <jia.yong.tan@intel.com> - 1.1.19-5
- Add SELinux policy for root access.

* Wed Jan 15 2025 Tadeusz Matenko <tadeusz.matenko@intel.com> - 1.1.19-4
- Fix SELinux policy

* Wed Jan 15 2025 Christopher Nolan <christopher.nolan@intel.com> - 1.1.19-3
- Update ownership of agent configuration files

* Tue Jan 14 2025 Suh Haw Teoh <suh.haw.teoh@intel.com> - 1.1.19-2
- Update file ownership and SELinux policy

* Tue Jan 07 2025 Suh Haw Teoh <suh.haw.teoh@intel.com> - 1.1.19-1
- Bump version to 1.1.19
- Update golang/x/net for CVE-2024-45338 fix

* Mon Jan 06 2025 Naveen Saini <naveen.kumar.saini@intel.com> - 1.1.18-6
- Update Source URL.

* Mon Dec 30 2024 Jia Yong Tan <jia.yong.tan@intel.com> - 1.1.18-5
- Add SELinux policy to allow root to read platform_telemetry_agent_conf_rw_t

* Tue Dec 24 2024 Jia Yong Tan <jia.yong.tan@intel.com> - 1.1.18-4
- Update permission to allow write access for confs directory and platform-telemetry-agent.yaml

* Fri Dec 20 2024 Suh Haw Teoh <suh.haw.teoh@intel.com> - 1.1.18-3
- Update /etc/edge-node/node/confs/ file permission to 755

* Thu Dec 19 2024 Suh Haw Teoh <suh.haw.teoh@intel.com> - 1.1.18-2
- Update file permission

* Wed Dec 18 2024 Suh Haw Teoh <suh.haw.teoh@intel.com> - 1.1.18-1
- Bump version to 1.1.18
- Ensure system accounts do no run a shell upon login
- Update file permission

* Fri Dec 13 2024 Jia Yong Tan <jia.yong.tan@intel.com> - 1.1.17-2
- Update SELinux policy

* Wed Nov 27 2024 Suh Haw Teoh <suh.haw.teoh@intel.com> - 1.1.17-1
- Bump version to 1.1.17
- Update fuzz test

* Fri Nov 22 2024 Jia Yong Tan <jia.yong.tan@intel.com> - 1.1.14-2
- Add custom SELinux subpackage for policy installation

* Tue Nov 05 2024 Suh Haw Teoh <suh.haw.teoh@intel.com> - 1.1.14-1
- Bump version to 1.1.14
- Update grpc-go version to 1.67.1
- Remove update telegraf path in postinstall

* Mon Oct 21 2024 Suh Haw Teoh <suh.haw.teoh@intel.com> - 1.1.13-1
- Bump version to 1.1.13
- Increased metric collection interval by setting coarse-grained profile

* Tue Oct 15 2024 Naveen Saini <naveen.kumar.saini@intel.com> - 1.1.12-3
- Remove dependency on cloud-init

* Fri Oct 04 2024 Anuj Mittal <anuj.mittal@intel.com> - 1.1.12-2
- Add dependency on cloud-init before the service is started

* Thu Oct 03 2024 Suh Haw Teoh <suh.haw.teoh@intel.com> - 1.1.12-1
- Bump version to 1.1.12
- Add ownership change logic to POA after fluent-bit get updated

* Fri Sep 06 2024 Suh Haw Teoh <suh.haw.teoh@intel.com> - 1.1.11-1
- Bump version to 1.1.11
- Add copyright to license dir
- Add dmidecode to get uuid

* Thu Sep 05 2024 Suh Haw Teoh <suh.haw.teoh@intel.com> - 1.1.8-7
- Add agent service file, environment wrapper script
- Update post install stage

* Thu Aug 29 2024 Tadeusz Matenko <tadeusz.matenko@intel.com> - 1.1.8-6
- Add sysusers

* Mon Aug 26 2024 Suh Haw Teoh <suh.haw.teoh@intel.com> - 1.1.8-5
- Update telegraf config path after install

* Fri Aug 23 2024 Suh Haw Teoh <suh.haw.teoh@intel.com> - 1.1.8-4
- Add platform-telemetry-agent to sudoers.d

* Mon Aug 19 2024 Suh Haw Teoh <suh.haw.teoh@intel.com> - 1.1.8-1
- Bump version to 1.1.8
- Change platform telemetry agent binary install path to /usr/bin
- Update platform telemetry agent service file

* Thu Jul 25 2024 Naveen Saini <naveen.kumar.saini@intel.com> - 1.1.4-3
- Bump release to rebuild with go 1.21.11
- Fixed _unitdir macro failure

* Wed Jul 24 2024 Suh Haw Teoh <suh.haw.teoh@intel.com> - 1.1.4-2
- Original version for Edge Microvisor Toolkit. License verified.
- Add systemd service file.

* Thu Jun 27 2024 Suh Haw Teoh <suh.haw.teoh@intel.com> - 1.1.4-1
- Skeleton spec for telemetry agent module.
